---
- name: Create asterixdb working directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ asterixdb_logdir }}"
    - "{{ asterixdb_installdir }}"
    - "{{ asterixdb_confdir }}"

- name: Check for local installation archive
  local_action: stat path=asterix-server-{{ asterixdb_version }}-binary-assembly.zip
  register: local_archive
  become: no

- include: local_archive_{{ local_archive.stat.exists }}.yml

- name: Check asterixdb processes
  shell: jps
  register: jps_output

