---
- name: Create Asterix working directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ asterixdb_logdir }}"
    - "{{ asterixdb_installdir }}"
    - "{{ asterixdb_confdir }}"

- name: Download and unpack Asterix
  unarchive:
    src: asterix-server-{{ asterixdb_version }}-binary-assembly.zip
    dest: "{{ asterixdb_installdir }}"
    creates: "{{ asterixdb_installdir }}/bin/asterixncservice"

- name: Check Asterix processes
  shell: jps
  register: jps_output


